version: "3.4"
services:
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - './.docker/compose/data/mongo/db:/data/db'
      - './.docker/compose/data/mongo/restore:/data/restore:ro'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
